SimFigure Widget: SimFigure Class Reference
SimFigure Class Reference
Public Types
enum AxisType { AxisType::Default, AxisType::LogX, AxisType::LogY, AxisType::LogLog }
The AxisType enum.
enum LineType {
LineType::None, LineType::Solid, LineType::Dotted, LineType::Dashed,
LineType::DashDotted
}
The LineType enum.
enum Marker {
Marker::None, Marker::Asterisk, Marker::Circle, Marker::Plus,
Marker::Triangle, Marker::DownTriangle, Marker::RightTriangle, Marker::LeftTriangle,
Marker::Box, Marker::Ex
}
The Marker enum.
enum Location {
Location::Bottom, Location::Top, Location::Left, Location::Right,
Location::TopLeft, Location::TopRight, Location::BottomLeft, Location::BottomRight,
Location::North, Location::South, Location::East, Location::West,
Location::NorthWest, Location::NorthEast, Location::SouthWest, Location::SouthEast
}
The Location enum.
enum FileType {
FileType::PNG, FileType::BMP, FileType::PDF, FileType::PS,
FileType::SVG
}
The FileType enum.
Public Slots
void on_picker_activated (bool on)
void on_picker_selected (const QPolygon &polygon)
void on_picker_appended (const QPoint &pos)
void on_picker_moved (const QPoint &pos)
void on_picker_removed (const QPoint &pos)
void on_picker_changed (const QPolygon &selection)
void showAxisControls (bool show)
void fit_data ()
Signals
void curve_selected (int ID)
Public Member Functions
SimFigure (QWidget *parent=nullptr)
~SimFigure ()
int plot (QVector< double > &, QVector< double > &, LineType lt=LineType::Solid, QColor col=Qt::red, Marker mk=Marker::None)
int scatter (QVector< double > &, QVector< double > &, QColor col=Qt::blue, Marker mk=Marker::Circle)
void clear (void)
void cla (void)
void grid (bool mayor=true, bool minor=true)
void legend (QList< QString > labels, Location loc=Location::South)
void moveLegend (Location loc)
void showLegend (bool=true)
bool legendVisible (void)
void select (int)
void clearSelection (void)
SimFigure::AxisType axisType (void)
void setAxisType (AxisType type)
QString xLabel ()
SimFigure::xLabel()
QString yLabel ()
SimFigure::yLabel()
int labelFontSize ()
returns the current font size used for xLabel() and yLabel()
QString title ()
SimFigure::title()
int titleFontSize ()
returns the current font size used for title()
void setXLabel (QString lbl)
void setYLabel (QString lbl)
void setLabelFontSize (int)
sets the current font size used for xLabel() and yLabel() to sz
void setTitle (QString title)
void setTitleFontSize (int)
sets the current font size used for title() to sz
double minX ()
returns the currently displayed minimum value of x
double maxX ()
returns the currently displayed maximum value of x
double minY ()
returns the currently displayed minimum value of y
double maxY ()
returns the currently displayed maximum value of y
void setXlimits (double xmin, double xmax)
Sets x-axis limits to given values. xmax must be larger than xmin.
void setYlimits (double ymin, double ymax)
Sets y-axis limits to given values. ymax must be larger than ymin.
int lineWidth (int ID)
void setLineWidth (int ID, int wd)
double lineWidthF (int ID)
void setLineWidthF (int ID, double wd)
SimFigure::LineType lineStyle (int ID)
void setLineStyle (int ID, LineType lt=LineType::Solid, Marker mk=Marker::None)
QColor lineColor (int ID)
void setLineColor (int ID, QColor color)
SimFigure::Marker marker (int ID)
SimFigure::marker.
int markerSize (int ID)
SimFigure::markerSize.
void setMarker (int ID, Marker mk, int size=10)
void saveToFile (QString filename, SimFigure::FileType type=SimFigure::FileType::PNG, QSizeF size=QSizeF(300, 200), int res=85)
save image to file
void exportToFile (QString filename, SimFigure::FileType type=SimFigure::FileType::PNG, QSizeF size=QSizeF(300, 200), int res=85)
save image to file
Protected Member Functions
void select (QwtPlotItem *)
void setLineStyle (QwtPlotCurve *, LineType lt)
void setLineColor (QwtPlotCurve *, QColor color)
void setMarker (QwtPlotCurve *curve, Marker mk, int size)
QwtPlotItem * itemAt (const QPoint &pos) const
void rescale (void)
void refreshGrid (void)
Member Enumeration Documentation
AxisType
enum SimFigure::AxisType strong
The AxisType enum.
used for selecting linear or logarithmic scales on th eX and Y axes.
Enumerator
Default
linear scales for x and y
LogX
log scale for x, linear scale for y
LogY
linear scale for x, log scale for y
LogLog
log scales for x and y
FileType
enum SimFigure::FileType strong
The FileType enum.
used to define file type in saveToFile() and exportToFile()
Enumerator
PNG
portable network graphic file
BMP
MicroSOft bitmap file.
PDF
portable document format
PS
PostScript file.
SVG
scaleable vector graphic file
LineType
enum SimFigure::LineType strong
The LineType enum.
used to define the line type used by plot().
Enumerator
None
no line is drawn (only markers)
Solid
a solid line is drawn
Dotted
a dotted line is drawn
Dashed
a dashed line is drawn
DashDotted
a dash-dotted line is drawn
Location
enum SimFigure::Location strong
The Location enum.
used to define the position of the legend (if visible) on the plot() canvas.
Enumerator
Bottom
centered horizontally at the bottom
Top
centered horizontally at the top
Left
centered vertically on the left
Right
centered vertically on the right
TopLeft
top left corner
TopRight
top right corner
BottomLeft
bottom left corner
BottomRight
bottom right corner
North
equivalent to Top
South
equivalent to Bottom
East
equivalent to Right
West
equivalent to Left
NorthWest
equivalent to TopLeft
NorthEast
equivalent to TopRight
SouthWest
equivalent to BottomLeft
SouthEast
equivalent to BottomRight
Marker
enum SimFigure::Marker strong
The Marker enum.
used to define the marker used for a particular plot().
Enumerator
None
no marker (line only)
Asterisk
∗
Circle
o
Plus
+
Triangle
upright triangle
DownTriangle
upside-down triangle
RightTriangle
point to the right triangle
LeftTriangle
point to the left triangle
Box
a square box
Ex
x
Constructor & Destructor Documentation
SimFigure()
SimFigure::SimFigure (QWidget * parent = nullptr) explicit
SimFigure is a widget that emulates a MATLAB-like interface to Qwt, allowing for a quick porting of MATLAB graphics to Qt5. Creating an instance of SimFigure is equivalent to MATLAB's
h = figure
Parameters
parent is a pointer to the parent widget simfigure.h "code/simfigure.h"
~SimFigure()
SimFigure::~SimFigure ()
the SimFIgure destructor
Member Function Documentation
axisType()
SimFigure::AxisType SimFigure::axisType (void)
returns the current AxisType
cla()
void SimFigure::cla (void)
clear curent axes – clears the figure but preserves the grid type
Referenced by clear().
clear()
void SimFigure::clear (void)
clear curent axes – clears the figure but preserves the grid type
identical to cla()
clearSelection()
void SimFigure::clearSelection (void)
clear selection of any curve. Upon completion, this function will emit a SIGNAL(curve_selected(int)) with value -1.
Referenced by on_picker_appended(), and select().
exportToFile()
void SimFigure::exportToFile (QString filename, SimFigure::FileType type = SimFigure::FileType::PNG, QSizeF size = QSizeF(300,200), int res = 85)
save image to file
used to save the plot to an image file. Location and filename are suggestions only. The user will face a QFileDialog to define actual filename and location.
Parameters
filename specified via QFileDialog
type default is SimFigure::FileType::PNG
size QSizeF(width in MM, height in MM). Defaults to 300mm/200mm (~12in/8in)
res resolution: use 75-95 for screen, ~100-150 for presentations, 300 for quality print. Defaults to 85
grid()
void SimFigure::grid (bool major = true, bool minor = true)
generate a grid with major (true|false) and minor (true|false) grid markers and lines.
grid() turns major and monor grid on
grid(false, false) turns the grid off
Referenced by SimFigure().
itemAt()
QwtPlotItem * SimFigure::itemAt (const QPoint & pos) const protected
returns a pointer to the QwtPlotItem selected by the last mouse click (private)
Referenced by on_picker_appended().
legend()
void SimFigure::legend (QList< QString > labels, Location loc = Location::South)
Add a legend to the current plot.
Location is an enum class.
legendVisible()
bool SimFigure::legendVisible (void)
check if legend is currently visible.
lineColor()
QColor SimFigure::lineColor (int ID)
returns line color of the curve with handle ID.
lineStyle()
SimFigure::LineType SimFigure::lineStyle (int ID)
returns the line style of a curve.
lineWidth()
int SimFigure::lineWidth (int ID)
return the line width of the curve with handle ID
lineWidthF()
double SimFigure::lineWidthF (int ID)
return the line width of the curve with handle ID
marker()
SimFigure::Marker SimFigure::marker (int ID)
SimFigure::marker.
Parameters
ID ... unique handle for the curve of interest
Returns
SimFigure::Marker enum to identify the marker for curve with handle=ID
markerSize()
int SimFigure::markerSize (int ID)
SimFigure::markerSize.
Parameters
ID ... unique handle for the curve of interest
Returns
size of the marker in pixels
moveLegend()
void SimFigure::moveLegend (Location loc)
Move the legend to a new location identified by Location (enum class Location)
Referenced by legend().
on_picker_activated
void SimFigure::on_picker_activated (bool on) slot
DEPRICATED
Referenced by SimFigure().
on_picker_appended
void SimFigure::on_picker_appended (const QPoint & pos) slot
upon mouse click inside the plot canvas, identify the QwtPlotItem most likely selected by that mouse event. There is a 5 pixel tolerance to either side of a curve for which a hit will be detected.
Referenced by SimFigure().
on_picker_changed
void SimFigure::on_picker_changed (const QPolygon & selection) slot
DEPRICATED
Referenced by SimFigure().
on_picker_moved
void SimFigure::on_picker_moved (const QPoint & pos) slot
DEPRICATED
Referenced by SimFigure().
on_picker_removed
void SimFigure::on_picker_removed (const QPoint & pos) slot
DEPRICATED
Referenced by SimFigure().
on_picker_selected
void SimFigure::on_picker_selected (const QPolygon & polygon) slot
DEPRICATED
Referenced by SimFigure().
plot()
int SimFigure::plot (QVector< double > & x, QVector< double > & y, LineType lt = LineType::Solid, QColor color = Qt::red, Marker mk = Marker::None)
The plot() method provides a plot functionality similar to MATLAP's plot function x and y are regerences to QVector<double>. The must be of equal length.
plot returns an integer serving as a unique handle for the curve. The following functions use that handle to read or change settings for that curve:
lineWidth(), lineWidthF(), setLineWidth(), setLineWidthF(), lineStyle(), setLineStyle(), lineColor(), setLineColor(), setMarker()
Parameters
lt a member of the SimFigure::LineType enum
color a QColor object defining the line color. You may also use pre-defined colors like Qt::red, ...
mk a member of the SimFigure::Marker enum.
Referenced by scatter().
refreshGrid()
void SimFigure::refreshGrid (void) protected
Regenerate th egrid with new settings (Type, limits) - (private)
Referenced by grid().
rescale()
void SimFigure::rescale (void) protected
reinitialize the scale engine for both axes (private)
Referenced by setXlimits(), and setYlimits().
saveToFile()
void SimFigure::saveToFile (QString filename, SimFigure::FileType type = SimFigure::FileType::PNG, QSizeF size = QSizeF(300,200), int res = 85)
save image to file
used to save the plot to an image file. Location and filename are defined from within the code. No user interaction required.
Parameters
filename includes fully specified path
type default is SimFigure::FileType::PNG
size QSizeF(width in MM, height in MM). Defaults to 300mm/200mm (~12in/8in)
res resolution: use 75-95 for screen, ~100-150 for presentations, 300 for quality print. Defaults to 85
scatter()
int SimFigure::scatter (QVector< double > & x, QVector< double > & y, QColor color = Qt::blue, Marker mk = Marker::Circle)
The scatter() method provides a plot functionality similar to MATLAP's scatter function x and y are regerences to QVector<double>. The must be of equal length.
scatter returns an integer serving as a unique handle for all points. The following functions use that handle to read or change settings for that curve:
lineWidth(), lineWidthF(), setLineWidth(), setLineWidthF(), lineStyle(), setLineStyle(), lineColor(), setLineColor(), setMarker()
Parameters
color a QColor object defining the line color. You may also use pre-defined colors like Qt::red, ...
mk a member of the SimFigure::Marker enum.
select() [1/2]
void SimFigure::select (int ID)
select the curve identified by its integer handle ID. Upon completion, this function will emit a SIGNAL(curve_selected(int)) with value = integer handle of that curve.
Referenced by on_picker_appended().
select() [2/2]
void SimFigure::select (QwtPlotItem * item) protected
select the curve identified by the provided pointer (private). Upon completion, this function will emit a SIGNAL(curve_selected(int)) with value = integer handle of that curve.
setAxisType()
void SimFigure::setAxisType (AxisType type)
set the AxisType for the current grid
setLineColor() [1/2]
void SimFigure::setLineColor (int ID, QColor color)
used to change the current color of a curve.
Referenced by plot().
setLineColor() [2/2]
void SimFigure::setLineColor (QwtPlotCurve * curve, QColor color) protected
used to change the current color of a curve. (private)
setLineStyle() [1/2]
void SimFigure::setLineStyle (int ID, LineType lt = LineType::Solid, Marker mk = Marker::None)
used to change the current line style of a curve.
Referenced by plot().
setLineStyle() [2/2]
void SimFigure::setLineStyle (QwtPlotCurve * curve, LineType lt) protected
used to change the current line style of a curve. (private)
setLineWidth()
void SimFigure::setLineWidth (int ID, int wd)
change the line width of the curve with handle ID
setLineWidthF()
void SimFigure::setLineWidthF (int ID, double wd)
change the line width of the curve with handle ID
setMarker() [1/2]
void SimFigure::setMarker (int ID, Marker mk, int size = 10)
used to change the current marker of a curve.
Referenced by plot(), and setLineStyle().
setMarker() [2/2]
void SimFigure::setMarker (QwtPlotCurve * curve, Marker mk, int size) protected
used to change the current marker of a curve. (private)
setTitle()
void SimFigure::setTitle (QString title)
set the figure title
setXLabel()
void SimFigure::setXLabel (QString label)
set the title for the x-axis
setXlimits()
void SimFigure::setXlimits (double xmin, double xmax)
Sets x-axis limits to given values. xmax must be larger than xmin.
See maxX() and minX() on how to obtain the current limits.
setYLabel()
void SimFigure::setYLabel (QString label)
set the title for the y-axis
setYlimits()
void SimFigure::setYlimits (double ymin, double ymax)
Sets y-axis limits to given values. ymax must be larger than ymin.
See maxY() and minY() on how to obtain the current limits.
showLegend()
void SimFigure::showLegend (bool on = true)
show (on=true) or hide (on=false) a legend for the current plots.
Referenced by legend().
title()
QString SimFigure::title (void)
SimFigure::title()
Returns
title of the current figure
Referenced by setTitle().
xLabel()
QString SimFigure::xLabel (void)
SimFigure::xLabel()
Returns
title of the current x-axis label
yLabel()
QString SimFigure::yLabel (void)
SimFigure::yLabel()
Returns
text of the current y-axis label
The documentation for this class was generated from the following files:
source/simfigure.h
source/simfigure.cpp